src/SummerReading/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SummerReadingData.Model;
using SummerReadingData;
using SummerReadingRewrite.Models;

namespace SummerReadingRewrite.Controllers
{
	[Authorize]
    public class ProgramController : Controller
    {
        private SummerReadingDb db = new SummerReadingDb();

        //
        // GET: /Program/

        public ActionResult Index()
        {
			var currentUser = db.GetCurrentStaffUser();
            var programs = db.GetProgramsForCurrentLibrary();
            return View(programs.ToList());
        }

        //
        // GET: /Program/Details/5

        public ActionResult Details(int id = 0)
        {
            Program program = db.Programs.Find(id);
            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

		[CustomAuthorize(Roles = "Admin")]
		public ActionResult Copy()
		{
			ViewBag.sourceId = new SelectList(db.GetProgramsForCurrentLibrary(), "Id", "Name");
			ViewBag.newOrgId = new SelectList(db.GetCurrentOrganizations(), "Id", "Name");
			return View();
		}

		[HttpPost]
		[CustomAuthorize(Roles = "Admin")]
		public ActionResult Copy(int sourceId, int newOrgId, string name)
		{
			var sourceProgram = db.Programs.Single(p => p.Id == sourceId);

			var prizes = new List<Prize>();
			sourceProgram.Prizes.ForEach(p => prizes.Add(
				new Prize
				{
					Description = p.Description,
					InitialQuantity = p.InitialQuantity,
					Requirement = p.Requirement,
					ProgramId = p.ProgramId
				})
			);
			var newProgram = new Program
			{
				Name = name.Length > 0 ? name : sourceProgram.Name,
				StartDate = sourceProgram.StartDate,
				EndDate = sourceProgram.EndDate,
				OrganizationId = newOrgId,
				MetricId = sourceProgram.MetricId,
				RecurringPrize = sourceProgram.RecurringPrize,
				Prizes = new List<Prize>(prizes)
			};

			db.Programs.Add(newProgram);
			db.SaveChanges();

			var test = db.Programs.Single(p => p.Id == newProgram.Id);

			ViewBag.EditMode = true;
			ViewBag.MetricId = new SelectList(db.Metrics, "Id", "Description", newProgram.MetricId);
			//return View("Edit", db.Programs.Single(p=>p.Id == newProgram.Id));
            return RedirectToAction("Edit", new { id = newProgram.Id });
		}


		[CustomAuthorize(Roles="Admin")]
        public ActionResult Create()
        {
            ViewBag.MetricList = new SelectList(db.Metrics, "Id", "Description");
			ViewBag.OrganizationId = new SelectList(db.GetCurrentOrganizations(), "Id", "Name");
			return View();
        }

		[CustomAuthorize(Roles = "Admin")]
		public ActionResult AddPrizeAjax(Prize prize)
		{
			if (ModelState.IsValid)
			{
				prize.CurrentQuantity = prize.InitialQuantity;
				db.Prizes.Add(prize);
				db.SaveChanges();
			}

			ViewBag.EditMode = true;
			return PartialView("_PrizeList", db.Prizes.Include(p=>p.Program).Where(p => p.ProgramId == prize.ProgramId));
		}

		[CustomAuthorize(Roles = "Admin")]
		public ActionResult AddActivityAjax(Activity activity)
		{
			if (ModelState.IsValid)
			{
				db.Activities.Add(activity);
				db.SaveChanges();
			}

			return PartialView("_ActivityList", db.Activities.Include(a=>a.Program).Where(a => a.ProgramId == activity.ProgramId));
		}

        //
        // POST: /Program/Create

        [HttpPost]
		[CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(Program program)
        {
			var currentUser = db.GetCurrentStaffUser();
			//if (currentUser.OrganizationId != program.OrganizationId)
			//{
			//	ModelState.AddModelError("", "Program organization does not match staff member organization");
			//	return View(program);
			//}

            if (ModelState.IsValid)
            {
				//program.OrganizationId = currentUser.OrganizationId;
                db.Programs.Add(program);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OrganizationId = new SelectList(db.GetCurrentOrganizations(), "Id", "Name", program.OrganizationId);
            return View(program);
        }

        //
        // GET: /Program/Edit/5
		[CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            Program program = db.Programs.Find(id);
            if (program == null)
            {
                return HttpNotFound();
            }

			ViewBag.EditMode = true;
			ViewBag.MetricId = new SelectList(db.Metrics, "Id", "Description", program.MetricId);
			return View(program);
        }

        //
        // POST: /Program/Edit/5

        [HttpPost]
		[CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(Program program)
        {			
            if (ModelState.IsValid)
            {
                db.Entry(program).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OrganizationId = new SelectList(db.Organizations, "Id", "Name", program.OrganizationId);
            return View(program);
        }

        //
        // GET: /Program/Delete/5
		[CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            Program program = db.Programs.Find(id);
            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

        //
        // POST: /Program/Delete/5

        [HttpPost, ActionName("Delete")]
		[CustomAuthorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Program program = db.Programs.Find(id);

            db.ReadingLogs.Where(rl => rl.ProgramId == id).ToList().ForEach(rl => db.ReadingLogs.Remove(rl));
            
			db.AwardedPrizes.Include(ap=>ap.Patron)
				.Include(ap => ap.Prize)
				.Where(ap => ap.Prize.ProgramId == id)// || ap.Patron.CurrentProgram.Id == id)
				.ToList()
				.ForEach(ap => db.AwardedPrizes.Remove(ap));

            db.Prizes.Where(p => p.ProgramId == id).ToList().ForEach(p => db.Prizes.Remove(p));
            db.Patrons.Where(p => p.Registrations.OrderByDescending(r=>r.RegistrationDate).FirstOrDefault().ProgramId == id).ToList().ForEach(p => db.Patrons.Remove(p));
			//db.Prizes.Where(p => p.ProgramId == id).ToList().ForEach(p => db.Prizes.Remove(p));
					
            db.Programs.Remove(program);
			
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/SummerReading/Views/Program/Copy.cshtml
@{
    ViewBag.Title = "Copy";
}

<h2>Copy Program</h2>

@using(Html.BeginForm("Copy", "Program")){
    <div class="editor-label">
        @Html.Label("Program to copy")
    </div>
    <div class="editor-field">
        @Html.DropDownList("sourceId", ViewBag.sourceId as SelectList, " -- ")
    </div>

    <div class="editor-label">
        @Html.Label("Organization for new program")
    </div>
    <div class="editor-field">
        @Html.DropDownList("newOrgId", ViewBag.newOrgId as SelectList, " -- ")
    </div>

    <div class="editor-label">
        @Html.Label("Newprogram name")
    </div>
    <div class="editor-field">
        @Html.TextBox("name")
    </div>
    <input type="submit" />
}

src/SummerReading/Views/Program/Create.cshtml
@model SummerReadingData.Model.Program

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Program</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartDate)
            @Html.ValidationMessageFor(model => model.StartDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndDate)
            @Html.ValidationMessageFor(model => model.EndDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RecurringPrize)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RecurringPrize)
            @Html.ValidationMessageFor(model => model.RecurringPrize)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrganizationId, "Organization")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.OrganizationId, ViewBag.OrganizationId as SelectList, " -- ")
            @Html.ValidationMessageFor(model => model.OrganizationId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MetricId, "Metric")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.MetricId, ViewBag.MetricList as SelectList, " -- ")
            @Html.ValidationMessageFor(model => model.MetricId)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.date').datepicker();
        });
    </script>
}

src/SummerReading/Views/Program/Delete.cshtml
@model SummerReadingData.Model.Program

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Program</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StartDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EndDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Organization.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Organization.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RecurringPrize)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RecurringPrize)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

src/SummerReading/Views/Program/Details.cshtml
@model SummerReadingData.Model.Program

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Program</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StartDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EndDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Organization.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Organization.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RecurringPrize)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RecurringPrize)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/SummerReading/Views/Program/Edit.cshtml
@model SummerReadingData.Model.Program

@{
    ViewBag.Title = "Edit";
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<div class="float-div-left width40p">
@using (Html.BeginForm())
{
    <h2>Program</h2>
    @Html.ValidationSummary(true)

    
    <div>
        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartDate)
            @Html.ValidationMessageFor(model => model.StartDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndDate)
            @Html.ValidationMessageFor(model => model.EndDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MetricId, "Metric")
        </div>
        <div class="editor-field">
            @Html.DropDownList("MetricId")
            @Html.ValidationMessageFor(model => model.MetricId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RecurringPrize)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RecurringPrize)
            @Html.ValidationMessageFor(model => model.RecurringPrize)
        </div>

        <div>
            @Html.HiddenFor(m => m.OrganizationId)
            <input type="submit" value="Save" />
        </div>      
    </div>
}
     @if (Model.Metric.Description.StartsWith("Poi"))
        {
            using (Ajax.BeginForm("AddActivityAJax", "Program", new AjaxOptions { UpdateTargetId = "activity-list" }, new { @id = "activity-form" }))
            {
                <h2>Activities</h2>
                @Html.Hidden("programid", Model.Id)

                <div id="activity-list">
                    @Html.Partial("_ActivityList", Model.Activities)           
                </div>
                
                @Html.ValidationSummary(true)
                @Html.Label("Description:") @Html.EditorFor(m => (new Activity()).Description)
                @Html.Label("Value:") @Html.EditorFor(m => (new Activity()).Value) @Html.ValidationMessageFor(m => (new Activity()).Value)
                <br />
                <input type="submit" value="Add Activity" />
            }
        }
</div>

@using (Ajax.BeginForm("AddPrizeAjax", "Program", new AjaxOptions { UpdateTargetId = "prize-list", OnComplete = "ClearFields" }, new { @class = "float-div-left", id = "prize-form", style = "width:50%;" }))
{
    <h2>Prizes</h2>
    @Html.Hidden("programid", Model.Id)
    <div id="prize-list">                   
        @Html.Partial("_PrizeList", Model.Prizes)        
    </div>
          
    <div id="prize-ajax-form-fields">
    @Html.ValidationSummary()
    @Html.Label("Description:") @Html.EditorFor(m => (new SummerReadingData.Model.Prize()).Description)
    @Html.Label("Requirement:") @Html.EditorFor(m => (new SummerReadingData.Model.Prize()).Requirement)
    @Html.Label("Quantity:") @Html.EditorFor(m => (new SummerReadingData.Model.Prize()).InitialQuantity)
    <br />
    <input type="submit" value="Add Prize" />
        </div>
    
}

@section Scripts {
   

    <script type="text/javascript">
        function ClearFields()
        {
                $('#prize-form').trigger("reset")
                $("#Description").focus();
        }

        $(document).ready(function () {
            $('.date').datepicker();
        });
        //$("#prize-form").submit(function (event) {

        //    //event.preventDefault();

        //    //var $form = $(this),
        //    //    description = $form.find('input[name="Description"]').val(),
        //    //    requirement = $form.find('input[name="Requirement"]').val(),
        //    //    initialQuantity = $form.find('input[name="InitialQuantity"]').val(),
        //    //    url = $form.attr('action');

        //    //var posting = $.post(url, { Description: desc,Requirement: requi, InitialQuantity: initialQuantity });

        //    //posting.done(function (data) {
        //    //    var content = $(data).find('#prize-list');
        //    //    $("#result").empty().append(data);
        //    //});

        //    $(this).trigger("reset");
        //    $("#Description").focus();
        //});        
    </script>
}

src/SummerReading/Views/Program/Index.cshtml
@model IEnumerable<SummerReadingData.Model.Program>

@{
    ViewBag.Title = "Index";
}
<h2>Programs</h2>
<p>
    @if (ViewContext.HttpContext.User.IsInRole("Admin")) 
    {
        @Html.ActionLink("Create Program", "Create") <text>|</text> @Html.ActionLink("Clone Program", "Copy")
    }
</p>
<table id="program-table">
    <tr>
        <th class="program-name-column">
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.Label("Location")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td class="program-name-column">
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>    
        <td>
            @Html.DisplayFor(modelItem=> item.Organization.Name)
        </td>  
        <td class="links-column">
            @Html.GenerateEditDeleteDetailsLinks("Admin", "Program", item.Id)
        </td>
    </tr>
}

</table>