src/SummerReading/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SummerReadingData.Model;
using SummerReadingData;

namespace SummerReadingRewrite.Controllers
{
    public class ActivityController : Controller
    {
        private SummerReadingDb db = new SummerReadingDb();

        //
        // GET: /Activity/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProgramId = new SelectList(db.Programs, "Id", "Name", activity.ProgramId);
            return View(activity);
        }

        //
        // POST: /Activity/Edit/5

        [HttpPost]
        public ActionResult Edit(Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
				return RedirectToAction("Edit", "Program", new { Id = activity.ProgramId });
            }
            ViewBag.ProgramId = new SelectList(db.Programs, "Id", "Name", activity.ProgramId);
            return View(activity);
        }

        //
        // GET: /Activity/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/SummerReading/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Clc.Polaris.Api;
using SummerReadingData.Model;
using SummerReadingRewrite.Models;
using SummerReadingData;
using System.Linq.Expressions;

namespace SummerReadingRewrite.Controllers
{
	[Authorize]
    public class PatronController : Controller
    {
		SummerReadingDb db = new SummerReadingDb();

		public ActionResult Index()
		{
			var currentUser = db.GetCurrentStaffUser();
			return View(db.GetPatronsForCurrentLibrary());
		}   

		[HttpPost]
		public ActionResult AddNonLibraryPatron(Patron patron, int programId)
		{			
			if (db.Patrons.Any(p => p.Username == patron.Username))
			{
				ModelState.AddModelError("", "Username is already in use, please try again");
				var viewModel = new AddNonLibraryPatronViewModel
				{
					Programs = db.GetProgramsForCurrentLibrary().ToList()
				};
				return View("AddNonLibraryPatron", viewModel);
			}

			if (ModelState.IsValid)
			{               
				db.Patrons.Add(patron);                
				db.SaveChanges();

                patron.Register(programId);
                db.SaveChanges();
			}
            db = new SummerReadingDb();

            patron = db.Patrons.Single(p => p.Id == patron.Id);

            return View("PatronAddedSuccessfully", patron);
		}

		[HttpGet]
		public ActionResult AddNonLibraryPatron()
		{
			var viewModel = new AddNonLibraryPatronViewModel
			{
				Programs = db.GetProgramsForCurrentLibrary().ToList()
			};

			return View(viewModel);
		}

		public ActionResult Search(string term) 
		{
			if (string.IsNullOrWhiteSpace(term))
			{
				return View("Index", db.GetPatronsForCurrentLibrary().ToList());
			}

			if (db.Patrons.Any(p => p.Username == term))
			{
				return RedirectToAction("Details", new { id = db.Patrons.Single(p => p.Username == term).Id });
			}

			if (term.Contains(" "))
			{
				var fname = term.Split(' ')[0];
				var lname = term.Split(' ')[1];
				if (db.Patrons.Count(p => p.FirstName == fname && p.LastName == lname) == 1)
				{
					
					return RedirectToAction("Details", new { id = db.Patrons.SingleOrDefault(p => p.FirstName == fname && p.LastName == lname).Id });					
				}
			}
            
			var staffMember = db.GetCurrentStaffUser();

			var patrons = db.Patrons.Where(p => (new List<string> { p.FirstName, p.LastName }).Any(f => term.Contains(f)) || 
				(new List<string> { p.FirstName, p.LastName }).Any(f => f.Contains(term)))
				.Where(p=>p.Registrations.FirstOrDefault().Program.Organization.ParentOrganizationId == (staffMember.Organization.ParentOrganizationId ?? staffMember.Organization.Id));

            return View("Index", patrons.ToList());
		}

		public ActionResult GetPrizeList(int patronId)
		{
			return PartialView("_PatronPrizeList", 
				db.Patrons
				.Include(p=>p.Registrations)
                .Include(p=>p.ReadingLogs)
				.Include(p=>p.ReceivedPrizes)
				.Single(p => p.Id == patronId)
			);
		}

		public ActionResult AjaxAddReadingLog(ReadingLog log)
		{
			if (ModelState.IsValid)
			{
				if (log.ActivityId != null)
				{
					log.Activity = db.Activities.Single(a => a.Id == log.ActivityId);
					log.Value = log.Activity.Value;
				}
				
				db.ReadingLogs.Add(log);
				db.SaveChanges();
			}

			return PartialView("_ReadingLogList", db.ReadingLogs.Where(rl=>rl.PatronId == log.PatronId).Include(rl=>rl.Program).OrderByDescending(rl=>rl.Id));
		}

		public ActionResult AddLibraryPatron()
		{
			var viewModel = new AddLibraryPatronViewModel
			{
				Programs = db.GetProgramsForCurrentLibrary().ToList()
			};

			return View(viewModel);
		}

		[HttpPost]
		public ActionResult AddLibraryPatron(string barcode, int programid)
		{
			if (db.Patrons.Any(p => p.Username == barcode))
			{
				ModelState.AddModelError("", "Username is already in use, please try again");
				var viewModel = new AddLibraryPatronViewModel
				{
                    Barcode = barcode,
					Programs = db.GetProgramsForCurrentLibrary().ToList()
				};
				return View("AddLibraryPatron", viewModel);
			}

			if (ModelState.IsValid)
			{
				var polaris = new PolarisApiClient();
				var result = polaris.staff_PatronBasicDataGet(barcode);

				if (result.PatronBasicData == null)
				{
					return View("GeneralError", result.ErrorMessage);
				}

				var patronData = result.PatronBasicData;

				var patron = new Patron
				{
					FirstName = patronData.NameFirst,
					LastName = patronData.NameLast,
					Username = barcode,
					Email = patronData.EmailAddress,
					Phone = patronData.PhoneNumber,
					Birthdate = patronData.BirthDate
				};

                
                db.Patrons.Add(patron);
                db.SaveChanges();

                patron.Register(programid);
                db.SaveChanges();

                db = new SummerReadingDb();

                patron = db.Patrons.Single(p => p.Id == patron.Id);

				return View("PatronAddedSuccessfully", patron);
			}

			return View();
		}

		public ActionResult Details(int id = 0)
		{
			Patron patron = db.Patrons.Find(id);
            
			if (patron == null)
			{
				return HttpNotFound();
			}
			if (patron.Registrations.First().Program.Metric.Description.StartsWith("Poi"))
			{
                var programid = patron.Registrations.First().Program.Id;

                ViewBag.ActivityId = new SelectList(db.Activities.Where(a => a.ProgramId == programid).ToList(), "Id", "Description");
			}
			return View(patron);
		}

		public ActionResult Edit(int id = 0)
		{
			Patron patron = db.Patrons.Include("Registrations").Single(p=>p.Id == id);
			if (patron == null)
			{
				return HttpNotFound();
			}
			ViewBag.ProgramId = new SelectList(db.GetProgramsForCurrentLibrary(), "Id", "Name", patron.Registrations == null || patron.Registrations.Count == 0 ? 0 : patron.CurrentProgram.Id);
			return View(patron);
		}

		[HttpPost]
        public ActionResult Edit(Patron patron, int programid)
		{
			if (ModelState.IsValid)
			{
                db.Patrons.Attach(patron);
                db.Entry(patron).Collection(p => p.Registrations).Load();
                db.Entry(patron).State = EntityState.Modified;

                if (db.ProgramRegistrations.Any(pr => pr.PatronId == patron.Id && pr.ProgramId == patron.CurrentProgram.Id))
                {
                    db.ProgramRegistrations.Remove(db.ProgramRegistrations.Single(pr => pr.PatronId == patron.Id && pr.ProgramId == patron.CurrentProgram.Id));
                }
                patron.Register(programid);
               

				db.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.ProgramId = new SelectList(db.Programs, "Id", "Name", patron.Registrations.First().Program.Id);
			return View(patron);
		}

		public ActionResult Delete(int id = 0)
		{
			Patron patron = db.Patrons.Find(id);
			if (patron == null)
			{
				return HttpNotFound();
			}
			return View(patron);
		}
		
		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Patron patron = db.Patrons.Find(id);
			db.AwardedPrizes.Where(ap => ap.PatronId == id).ToList().ForEach(ap => db.AwardedPrizes.Remove(ap));
			db.Patrons.Remove(patron);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			db.Dispose();
			base.Dispose(disposing);
		}
    }
}

src/SummerReading/Controllers/PrizeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SummerReadingData;
using SummerReadingData.Model;

namespace SummerReadingRewrite.Controllers
{
	[Authorize]
    public class PrizeController : Controller
    {
		private SummerReadingDb db = new SummerReadingDb();

        public ActionResult Award(int prizeid, int patronid)
        {
			var result = db.AwardPrize(patronid, prizeid);
			return PartialView("_AwardPrize", result);
        }

		//
		// GET: /Default2/Edit/5

		public ActionResult Edit(int id = 0)
		{
			Prize prize = db.Prizes.Find(id);
			if (prize == null)
			{
				return HttpNotFound();
			}
			ViewBag.ProgramId = new SelectList(db.Programs, "Id", "Name", prize.ProgramId);
			return View(prize);
		}

		//
		// POST: /Default2/Edit/5

		[HttpPost]
		public ActionResult Edit(Prize prize)
		{
			if (ModelState.IsValid)
			{
				db.Entry(prize).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Edit", "Program", new { Id = prize.ProgramId });
			}
			ViewBag.ProgramId = new SelectList(db.Programs, "Id", "Name", prize.ProgramId);
			return View(prize);
		}

		//
		// GET: /Default2/Delete/5

		public ActionResult Delete(int id = 0)
		{
			Prize prize = db.Prizes.Find(id);
			if (prize == null)
			{
				return HttpNotFound();
			}
			return View(prize);
		}

		//
		// POST: /Default2/Delete/5

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Prize prize = db.Prizes.Find(id);
			db.Prizes.Remove(prize);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			db.Dispose();
			base.Dispose(disposing);
		}
    }
}

src/SummerReading/Views/Shared/ShortDateTime.cshtml
@model System.DateTime?

@Model.ToShortDateString()

src/SummerReading/Views/Shared/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
}

<h2>Unauthorized</h2>
<p> You do not have the proper permissions to view this page. </p>
<a href="@Request.ServerVariables["http_referer"]">Back</a>

src/SummerReading/Views/Shared/_ActivityList.cshtml
@model IEnumerable<Activity>

@if (Model.Count() > 0)
{
    <table>
        <tr>
            <th> Description </th>
            <th> Value </th>
            @if (ViewBag.EditMode == true) { <th></th> }
        </tr>

        @foreach (var a in Model)
        {
            <tr> 
                <td> @a.Description </td>
                <td> @a.Value @if (a.Value == 1) { @a.Program.Metric.Description.TrimEnd('s'); } else { @a.Program.Metric.Description; } </td>
                @if (ViewBag.EditMode == true) { <td> @Html.ActionLink("Edit", "Edit", "Activity", new { id=a.Id }, null) </td> }
            </tr>
        }
    </table>
}

src/SummerReading/Views/Shared/_AwardPrize.cshtml
@model AwardPrizeResult

@if (Model.Success)
{        
    if (Model.Prize.Program.RecurringPrize)
    {
        @Model.Message
    }
    else
    {
        @:Prize successfully awarded.
    }
}
else
{
        <text>Prize was unable to be awarded.</text> @Model.Message     
}

src/SummerReading/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - CLC Summer Reading</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css");
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("CLC Summer Reading", "Index", "Home")</p>
                    <div id="username-search">
                        @using (Html.BeginForm("Search", "Patron", FormMethod.Post, new { style = "display:inline" }))
                        {
                            @Html.Label("Username", new { @id = "username-search-label" }) 
                            @Html.TextBox("term", string.Empty, new { @id = "username-search-textbox" }) 
                            <input type="submit" value="Search" />
                        }
                        <span>@Html.ActionLink("Add Library Patron", "AddLibraryPatron", "Patron") | @Html.ActionLink("Add Non-Library Patron", "AddNonLibraryPatron", "Patron")</span>
                    </div>
                </div>
                <div class="float-right">
                    <section id="login">
                        Hello, <span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">                            
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Patrons", "Index", "Patron")</li>
                            <li>@Html.ActionLink("Programs", "Index", "Program")</li>
                            @if(ViewContext.HttpContext.User.IsInRole("Admin")) { <li>@Html.ActionLink("Staff", "Index", "StaffMember")</li> }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqueryval")
        @RenderSection("scripts", required: false)
    </body>
</html>

src/SummerReading/Views/Shared/_PatronList.cshtml
@model IEnumerable<Patron>

<table>
    <tr>
        <th> Username </th>
        <th class="namecolumn"> Name </th>
    </tr>
    @foreach (var p in Model)
    {
        <tr>
            <td class="namecolumn"> @p.Username </td>
            <td> @string.Format("{0} {1}", p.FirstName, p.LastName) </td>            
        </tr>
    }
</table>

src/SummerReading/Views/Shared/_PatronPrizeList.cshtml
@model Patron

@using (var db = new SummerReadingData.SummerReadingDb()) 
{
    var logsum = Model.ReadingLogs.Sum(rl=>rl.Value);
    <h2> Prizes </h2>
    <table id="patron-prize-list" class="width100p">
        <tr>
            <th> @Html.LabelFor(m=>(new Prize()).Description) </th>
            <th class="reqcolumn"> @Html.Label("Req")  </th>
            <th> @Html.Label(Model.CurrentProgram.RecurringPrize ? "Last Received" : "Received") </th>
        </tr>
    @foreach (var prize in db.GetAllPrizesForPatron(Model).OrderBy(p=>p.Requirement))
    {
        <tr>
            <td>
                @prize.Description
            </td>
            <td class="reqcolumn">
                @prize.Requirement
            </td>
            @if (db.PatronOwedPrize(Model, prize)) 
            {
                if(Model.CurrentProgram.RecurringPrize ? true : db.AwardedPrizes.Any(ap=>ap.PrizeId == prize.Id && ap.PatronId == Model.Id) == false)
                {
                    <td>                      
                        @using (Ajax.BeginForm("Award",
                            "Prize",
                            null,
                            new AjaxOptions
                            {
                                UpdateTargetId = String.Format("award-prize-link-{0}", prize.Id)
                            },
                            new { @id = String.Format("award-prize-link-{0}", prize.Id) }
                            )
                        )
                        {
                            @Html.Hidden("prizeid", prize.Id)
                            @Html.Hidden("patronid", Model.Id)
                            <span>Not yet awarded</span>
                            <input type="submit" value="Award" />
                        }
                    </td>   
                }                                       
            }
            else 
            {
                if (db.AwardedPrizes.Any(ap=>ap.PatronId == Model.Id && ap.PrizeId == prize.Id))
                {
                <td>
                    @{var awardedPrize = db.AwardedPrizes
                                            .Where(ap => ap.PatronId == Model.Id && ap.PrizeId == prize.Id)
                                            .OrderByDescending(ap=>ap.DateAwarded)
                                            .First().DateAwarded;}

                    @String.Format("{0}", awardedPrize.HasValue ? awardedPrize.Value.ToShortDateString() : "Not yet awarded")
                </td>
                }  
                else
                {
                    <td></td>
                }
            }

                
            @* @if (Model.Program.RecurringPrize)
            {
                      
            }
            else
            {
                if (db.AwardedPrizes.Any(ap=>ap.PatronId == Model.Id && ap.PrizeId == prize.Id))
                {
                <td>
                    @{var awardedPrize = db.AwardedPrizes.Single(ap => ap.PatronId == Model.Id && ap.PrizeId == prize.Id).DateAwarded;}

                    @String.Format("{0}", awardedPrize.HasValue ? awardedPrize.Value.ToShortDateString() : "Not yet awarded")
                </td>
                }  
                                        
            }*@
                
        </tr>
    }
    </table>
}

src/SummerReading/Views/Shared/_PrizeList.cshtml
@model IEnumerable<SummerReadingData.Model.Prize>

@if (Model.Count() > 0) 
{
    <table>
        <tr>
            <th> Description </th>
            <th> Requirement </th>
            @if (!Model.First().Program.Organization.Name.StartsWith("Fai")) { <th> Quantity Remaining </th> }
            @if (ViewBag.EditMode == true) { <th></th> }
           
       
        </tr>
    @foreach (var p in Model.OrderBy(p=>p.Requirement))
    {
        <tr>
            <td> @p.Description </td>
            <td> @p.Requirement @if (p.Requirement == 1) { @p.Program.Metric.Description.TrimEnd('s'); } else { @p.Program.Metric.Description; } </td>
            @if (!Model.First().Program.Organization.Name.StartsWith("Fai")) { <td>  @p.CurrentQuantity </td> }
            @if (ViewBag.EditMode == true) { <td> @Html.ActionLink("Edit", "Edit", "Prize", new { id=p.Id }, null) </td> }
        </tr>
    }
    </table>
}

src/SummerReading/Views/Shared/_ProgramList.cshtml
@model IEnumerable<Program>

<table>
    <tr>
        <th> Name </th>
        <th> Start Date </th>
        <th> End Date </th>
        <th> Recurring Prize </th>
    </tr>

    @foreach (var p in Model)
    {
        <tr>
            <td> @p.Name </td>
            <td> @p.StartDate.ToShortDateString() </td>
            <td> @p.EndDate.ToShortDateString() </td>
            <td> @p.RecurringPrize </td>
        </tr>
    }
</table>

src/SummerReading/Views/Shared/_ReadingLogList.cshtml
@model IEnumerable<ReadingLog>

@if (Model.Count() > 0) 
{
<table>
    <tr>
        <th class="log-date-column"> @Html.Label("Date") </th>
        <th class="log-description-column"> 
            @if (Model.First().Program.Metric.Description.StartsWith("Poi"))
            {
                @Html.Label("Activity")
            }
            else
            {
                @Html.Label("Book Title")
            }
        </th>
        <th class="log-value-column"> @Html.Label("Value") </th>
    </tr>
@foreach (var rl in @Model)
{
    <tr>
        <td class="log-date-column"> @rl.LogTime.ToShortDateString() </td>
        <td class="log-description-column"> 
            @if (Model.First().Program.Metric.Description.StartsWith("Poi"))
            {
                @((rl.Activity ?? new Activity()).Description)
            }
            else
            {
                @rl.BookTitle
            }
        </td>
        <td class="log-value-column"> @rl.Value @if (rl.Value == 1) { @rl.Program.Metric.Description.TrimEnd('s'); } else { @rl.Program.Metric.Description; } </td>
    </tr>    
}

</table>
}